config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}, sign_up: 'signup', sign_in: 'login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
  
  resources :categories
  
  resources :newsletters do
    get :prevent_display
    get :restore_cookie
  end

  resources :users do
    get :following
    get :activity
  end

  resources :comments do
    resources :comments
  end

  resources :searches

  resources :networks do
    member do
      put :follow
      put :unfollow
      get :logs
    end

    resources :whitepapers

    resources :coins do
      member do
        put :follow
        put :unfollow
        get :logs
        get :ico
        get :edit_ico
      end
    end

    resources :links, path: :questions do 
      resources :comments do
        resources :comments
      end
    end

  end

  resources :links, path: :questions do 
    resources :comments do
      resources :comments
    end
  end

  resources :whitepapers

  require 'sidekiq/web'
  
  mount Sidekiq::Web => '/sidekiq'
  
  get '/account/', to:"users#edit"
  
  get '/account/:id', to:"users#edit"

  get 'finish/:id/', to: 'users#finish', :as => :finish

  get 'about', to: 'users#index', :as => :about

  get 'sales', to: 'coins#sales', :as => :sales

  get 'search', to: 'searches#results', :as => :results

  get 'coin_search', to: 'searches#coin_search', :as => :coin_search

  get 'network_search', to: 'searches#network_search', :as => :network_search

  get 'network_match', to: 'searches#network_match', :as => :network_match

  get 'networks/:network_id/coin/:id/add_network', to: 'coins#add_network', :as => :add_network_to_coin

  get 'questions', to: 'links#index', :as => :questions

  get 'loaderio-f78e3355deb50cdf9149e06780c03507', to: 'users#loader'

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
    get 'signin', to: 'devise/sessions#new'
  end

  get ':username', to: 'users#show', :as => :current_user
  
  get ':username/edit', to: 'users#edit', :as => :edit_current_user
  
  get ':username/activity', to: 'users#activity', :as => :current_user_activity

end

app/models/network.rb
class Network < ApplicationRecord

	has_many :coins
	has_and_belongs_to_many :links
	has_many :comments, through: :links
	has_many :whitepapers
	accepts_nested_attributes_for :whitepapers
	belongs_to :category, optional: true, touch: true
	belongs_to :user, optional: true
	include CarrierWave::MiniMagick
	mount_uploader :logo, NetworkLogoUploader
	extend FriendlyId
	include PgSearch
	multisearchable :against => [:name, :description]
	pg_search_scope :search, :against => :name, :using => { :tsearch => { :prefix => true }, :trigram => { :threshold => 0.1 } }

	nilify_blanks

	auto_strip_attributes :link, :github, :reddit, :forum, :slack

	validates :logo, presence: true
	validates :name, presence: true, uniqueness:true

	friendly_id :name, use: [:slugged, :history]

	has_paper_trail :class_name => 'Version', :ignore => [:slug, :updated_at, :category_id]

	enum network_status_options: [:concept, :preproduction, :live, :dead]

  	attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
	after_update :crop_logo

	def crop_logo
		logo.recreate_versions! if crop_x.present?
	end

	acts_as_followable

	def should_generate_new_friendly_id?
	  slug.blank? || name_changed?
	end
	
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController

	before_action :authenticate_user!, only: [:edit,:new,:create,:update,:follow,:unfollow]

	def index
		# @networks = Network.all
		@categories = Category.all.order("name ASC")
		page_title = "networks"
		respond_to do |format|
		    format.html
		    format.js
		    format.json
		end
	end

	def links
		@links = Network.friendly.find(params[:id]).links
		respond_to do |format|
		    format.html
		    format.js
		    format.json
		end
	end

	def logs
		@active_item = "log"
        network_logs = NetworkService.new
        @network = Network.friendly.find(params[:id]) 
        logs = network_logs.get_logs(@network, "Network").reverse
        @logs = logs.paginate(:page => params[:page], :per_page => 10)
		respond_to do |format|
		    format.html
		    format.js
		    format.json
		end
	end	

	def whitepapers
        @whitepapers = Network.friendly.find(params[:id]).whitepapers
		respond_to do |format|
		    format.html
		    format.js
		    format.json
		end
	end		

	def show
		@network = Network.friendly.find(params[:id])
		@whitepapers = @network.whitepapers.all
		if current_user && current_user.following?(@network)
			@following = true
		else 
			@following = false
		end
		respond_to do |format|
		    format.html
		    format.js
		    format.json
		end
	end

	def new
		@use_ajax = false
		@network = Network.new
		@network.whitepapers.build
	end

	def edit
		@use_ajax = true
		@network = Network.friendly.find(params[:id])
		@network.whitepapers.build
		respond_to do |format|
		    format.html
		    format.js
		    format.json
		end
	end

	def create
		@network = Network.new(network_params)
		@network.user = current_user
		@network.founders = params[:founders] 
	    if @network.save
	      if !@network.logo.validate_dimensions
	        render :crop
	      else
			redirect_to @network, notice: "Network created"
		  end
		else
	        render 'new'
	    end
	end

	def update
		@network = Network.friendly.find(params[:id])
		@network.founders = params[:founders] 
	  	if @network.update_attributes(network_params)
	    	if params[:network][:logo].present? and !@network.logo.validate_dimensions
	          render :crop
	        else
	          redirect_to @network, notice: "Network updated"
	        end
		else
	    	render 'edit'
	  	end
	end

	def destroy
		@network.destroy
	end

	def follow
		@network = Network.friendly.find(params[:id])
		@user = current_user
		@coins = @network.coins
		if @user.follow(@network)
			if @network.coins.any?
				@network.coins.each do |coin| 
					@user.follow(coin)
				end
			end
			@success = true
		end
		respond_to do |format|
		    format.html
		    format.js { flash.now[:notice] = "You will receive updates about this network via email" }
		    format.json
		end
	end

	def unfollow
		@network = Network.friendly.find(params[:id])
		@user = current_user
		@coins = @network.coins
		if @user.stop_following(@network)
			if @network.coins.any?
				@network.coins.each do |coin| 
					@user.stop_following(coin)
				end
			end
			@success = true
		end
		respond_to do |format|
		    format.html
		    format.js { flash.now[:alert] = "You will no longer receive updates about this network via email" }
		    format.json
		end
	end

	private

	    def network_params
	    	params.require(:network).permit(:name, :description, :category_id, :link, :slack, :team, :status, :forum, :reddit, :coin_id, :logo, :founders, :github, :differentiator, :coin, :team_location, :blockchain, :crop_x, :crop_y, :crop_w, :crop_h, whitepapers_attributes: [:id, :network_id, :whitepaper_title, :whitepaper, :slug], link_ids: [], founders: [], category_ids: [], coin_ids: [], coins: [])
	    end

end

app/views/networks/_all-categories.html.erb
<% @categories.each do |category| %>
	<ul class="full-category-cnt" id=<%= category.name %>>
		<% unless category.coins.empty? %>
			<li class="category-coin-block">
				<div class="row">
					<div class="col-md-10 col-md-offset-2">
						<div class="row coins-in-categories" > 
							<h4 class="list-name"><%= category.name %></h4>
							<% category.coins.each_with_index do |coin, i| %>		
								<%= render 'coin_widget', :coin => coin, :i => i %>
							<% end %>
						</div>
					</div>
				</div>
			</li>
		<% end %>
	</ul>
<% end %>

app/views/networks/_category_menu.html.erb
<div class="col-md-2 col-md-offset-1 left-nav">
	<ul class="info-menu status-info-menu" id="network-status-info-menu">
		<li id="status-show-all" class="status-link active-item" data-status="all">
			<p>All statuses</p>
		</li>
		<li class="status-link" data-status="live">
			<p>Live</p>
		</li>
		<li class="status-link" data-status="preproduction">
			<p>Preproduction</p>
		</li>
		<li class="status-link" data-status="concept">
			<p>Concept</p>
		</li>
	</ul>
	<ul class="info-menu category-info-menu" id="network-category-info-menu">
		<li data-category="all" id="category-show-all" class="active-item category-link">
			<p>All categories</p>
		</li>
		<% @categories.each do |category| %>
			<% unless category.networks.nil? %>
				<li class="category-link" data-category=<%= category.name.gsub(/\s+/, "").downcase %>><p><%= category.name.capitalize %></p></li>
			<% end %>	
		<% end %>
	</ul>
</div>
<div class="col-xs-12 dropdown-navigator" id="category-dropdown">
	<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    categories
    	<span class="caret"></span>
  	</button>
	<ul class="dropdown-menu top-nav" aria-labelledby="dropdownMenuDivider">
		<li data-category="all">all categories</li>
		<li role="separator" class="divider"></li>
		<% @categories.each do |category| %>
			<% unless category.networks.nil? %>
				<li class="category-link" data-category=<%= category.name.gsub(/\s+/, "").downcase %>><%= category.name.downcase %></li>
			<% end %>	
		<% end %>
	</ul>
</div>

app/views/networks/_links.html.erb
<ul>
	<% if @network.links.empty? %>
		<div class="row">
			<div class="col-md-8 col-md-offset-4">
				<p class="add-first">No questions yet. <%= link_to "Add one?", new_link_url(network: @network), remote: true %></p>
			</div>
		</div>
	<% else %>
		<%= render(partial: 'links/show_all_links', collection: @network.links, as: :link, locals: {show_tag: false}) %>
	<% end %>
</ul>

app/views/networks/_log.html.erb
	<li class="log-block block">
		<div class="row">
			<% if show_tag %>
				<div class="col-md-4">
		    		<% unless log.networks.nil? %>
				    	<%= link_to log.networks, class: "user-log-classification-anchor" do %>
				    		<div class="user-log-classification">
								<div class="user-log-classification-network">
									<%= image_tag(log.networks.logo.small.url, size: "20x20") if log.networks.logo? %>
									<%= truncate(log.networks.name, length: 18) %>
									<div class="clear"></div>
								</div>
								<div class="clear"></div>
							</div>
						<% end %>
					<% end %>
				</div>
				<div class="col-md-8 log-inner-block">
			<% else %>
				<div class="col-md-8 col-md-offset-4 log-inner-block">
			<% end %>
				<%= render partial: '/networks/log_data', locals: { log: log } %>
				<%= render partial: '/shared/who_posted', locals: { user: log.user, created_at: log.created_at } %>
			</div>
		</div>
	</li>

app/views/networks/_log_data.html.erb
<% if defined?(email) %> 
	<ul class="log-list" style="padding: 0 !important; margin: 0  !important; text-indent: 0  !important; list-style-type: 0  !important;"> 
<% else %>
	<ul class="log-list">
<% end %>
		<% log.changes.each do |change| %>
			<% unless change[:change].blank? || change[:change].empty? || change[:change] == "" || change[:change].nil? || change[:change].second == "" || change[:change].second == [""] or (change[:change_type] == "added" and (change[:change].second == "" or change[:change].second.blank?)) %> 
				<% if defined?(email) %> 
					<li style="padding: 0; margin: 0; text-indent: 0; list-style-type: 0;"> 
				<% else %>
					<li>
				<% end %>
						<% case change[:change_attr] %>
							<% when "whitepapers" %>
								<% if change[:change_type] == "added" || change[:change_type] == "edited" %>
									Added a <span class="change_attr"><%= change[:change_attr].gsub('s','') %></span>
								<% end %>
							<% when "founders" %>
								<% if change[:change_type] == "added" %>
									Added <span class="change_attr"><%= change[:change_attr] %></span>: 
									<% change[:change].second.each_with_index do |change, i| %>
										<%= change %>
									<% end %>
								<% elsif change[:change_type] == "edited" %>
									Changed <span class="change_attr"><%= change[:change_attr] %></span> from 
										<% change[:change].first.each_with_index do |c, i| %>
											<%= " and " if i + 1 == change[:change].first.length && change[:change].first.length != 1 %><%= c %><%= ",	" unless i + 1 == change[:change].first.length || i + 2 == change[:change].first.length  %>
										<% end %>
									to 
										<% change[:change].second.each_with_index do |c, i| %>
											<%= " and " if i + 1 == change[:change].second.length && change[:change].second.length != 1 %><%= c %><%= ", " unless i + 1 == change[:change].second.length || i + 2 == change[:change].second.length || change[:change].first.length == 1 %>
										<% end %>
								<% end %>
							<% when "Status" %>
								<% if change[:change_type] == "added" %>
									Set <span class="change_attr"><%= change[:change_attr].downcase %></span>: <div class="status-cnt"><div class="status-icon <%= change[:change].second %>-icon"></div><p class="status <%= change[:change].second %>-status"><%= change[:change].second %></p></div>
								<% elsif change[:change_type] == "edited" %>
									Changed <span class="change_attr"><%= change[:change_attr].downcase %></span> from <div class="status-cnt"><div class="status-icon <%= change[:change].first %>-icon"></div><p class="status <%= change[:change].first %>-status"><%= change[:change].first %></p></div> to <div class="status-cnt"><div class="status-icon <%= change[:change].second %>-icon"></div><p class="status <%= change[:change].second %>-status"><%= change[:change].second %></p></div>
								<% end %>
							<% when "Link" %>
								<% if change[:change_type] == "added" %>
									Added <span class="change_attr">homepage</span>: <%= link_to get_host_without_www(change[:change].second), change[:change].second %>
								<% elsif change[:change_type] == "edited" %>
									Changed <span class="change_attr">homepage</span> from <%= link_to get_host_without_www(change[:change].first), change[:change].first %> to <%= link_to get_host_without_www(change[:change].second), change[:change].second %>
								<% end %>
							<% when "Description" %>
								<% if change[:change_type] == "added" %>
									Added a <span class="change_attr">description</span>: "<%= change[:change].second %>"
								<% elsif change[:change_type] == "edited" %>
									Changed <span class="change_attr">description</span> from "<%= change[:change].first %>" to "<%= change[:change].second %>"
								<% end %>	
							<% when "slack" %>
								<% if change[:change_type] == "added" %>
									Added <span class="change_attr">Slack</span>: <%= link_to get_host_without_www(change[:change].second), change[:change].second %>
								<% elsif change[:change_type] == "edited" %>
									Changed <span class="change_attr">Slack</span> from <%= link_to get_host_without_www(change[:change].first), change[:change].first %> to <%= link_to get_host_without_www(change[:change].second), change[:change].second %>
								<% end %>
							<% when "forum" %>
								<% if change[:change_type] == "added" %>
									Added <span class="change_attr">forum</span>: <%= link_to get_host_without_www(change[:change].second),  change[:change].second %>
								<% elsif change[:change_type] == "edited" %>
									Changed <span class="change_attr">forum</span> from <%= link_to get_host_without_www(change[:change].first), change[:change].first unless change[:change].first.nil? %> to <%= link_to get_host_without_www(change[:change].second), change[:change].second unless change[:change].second.nil? %>
								<% end %>
							<% when "reddit" %>
								<% if change[:change_type] == "added" %>
									Added <span class="change_attr">Reddit</span>: <%= link_to change[:change].second.nil? ? change[:change].second : change[:change].second.gsub("https://www.reddit.com/",""), change[:change].second %>
								<% elsif change[:change_type] == "edited" %>
									Changed <span class="change_attr">Reddit</span> from <%= link_to change[:change].first.nil? ? change[:change].first.gsub("https://www.reddit.com/","") : change[:change].first, change[:change].first %> to <%= link_to change[:change].second.nil? ? change[:change].second : change[:change].second.gsub("https://www.reddit.com/",""), change[:change].second %>
								<% end %>		
							<% when "github" %>
								<% if change[:change_type] == "added" %>
									Added <span class="change_attr">repository</span>: <%= link_to get_host_without_www(change[:change].second),  change[:change].second %>
								<% elsif change[:change_type] == "edited" %>
									Changed <span class="change_attr">repository</span> from <%= link_to get_host_without_www(change[:change].first), change[:change].first %> to <%= link_to get_host_without_www(change[:change].second), change[:change].second %>
								<% end %>
							<% when "team" %>
								<% if change[:change_type] == "added" %>
									<p>Added the <span class="change_attr">team</span>: "<%= change[:change].second %>"</p>
								<% elsif change[:change_type] == "edited" %>
									<p>Changed <span class="change_attr">team</span> from "<%= change[:change].first %>" to "<%= change[:change].second %>"</p>
								<% end %>				
							<% when "Created" %>
								Created 
									<%= link_to log.networks.name, log.networks %>
							<% when "logo" %>
								<% if change[:change_type] == "added" or change[:change].first == "/assets/fallback/default.png" %>
									Added <span class="change_attr"><%= change[:change_attr] %></span>: <%= image_tag log.networks.logo, size: '16x16', id: 'network-logo-inline' %>
								<% elsif change[:change_type] == "edited" %>
									Changed <span class="change_attr"><%= change[:change_attr] %></span> from 

										<%= image_tag change[:change].first, size: '16x16', id: 'network-logo-inline' %> to <%=  %> <%= image_tag log.networks.logo, size: '16x16', id: 'network-logo-inline' %>
								<% end %>
							<% else %>
								<% if change[:change_type] == "added" %>
									<p>Added <span class="change_attr"><%= change[:change_attr].downcase %></span>: "<%= change[:change].second %>"</p>
								<% elsif change[:change_type] == "edited" %>
									<p>Changed <span class="change_attr"><%= change[:change_attr].downcase %> from "<%= change[:change].first %>" to : "<%= change[:change].second %>"</p>
								<% end %>
						<% end %>
					</li>
			<% end %>
		<% end %>
	</ul>

app/views/networks/_logs.html.erb
<div class="row">
	<div class="col-md-8">
		<ul>
			<% if @logs.any? %>
				<%= render(partial: 'log', collection: @logs, as: :log) %>
			<% else %>
				<li>
					<div class="row">
						<div class="col-md-8 col-md-offset-4">
							<p>No logs yet. Logs will show up when someone makes changes to this coin.</p>
						</div>
					</div>
				</li>
			<% end %>
		</ul>
	</div>
</div>

app/views/networks/_network_frame_bottom.html.erb
		</div>
	</div>
</div>

app/views/networks/_network_main_info_header.html.erb
<div class="row">
	<div class="col-md-8 data col-md-offset-4 logo-cnt">
		<% if network.logo.nil? || network.logo.blank? %>
			<%= image_tag "fallback/default.png", size: '60x60', id: 'network-logo' %>
		<% else %>
			<%= image_tag network.logo_url(:thumb), size: '60x60', id: 'network-logo' %>
		<% end %>
		<h1 id="network-name"><%= network.name %></h1>
	</div>
</div>

app/views/networks/_related_dropdown.html.erb
<div class="col-xs-12 dropdown-navigator">
	<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    related
    	<span class="caret"></span>
  	</button>
	<ul class="dropdown-menu top-nav" id="network-related-dropdown" aria-labelledby="dropdownMenuDivider">
		<li data-link=<%= network_path(network) %>>details </li>
		<li data-link=<%= network_whitepapers_path(network) %>>whitepapers</li>
		<li data-link=<%= network_links_path(network) %>>questions</li>
		<li data-link=<%= "/networks/#{network.name.downcase.split(' ').join('-')}/logs" %>>logs</li>
	</ul>
</div> 

app/views/networks/crop.html.erb
<div class="row">
	<div class="col-md-2 col-md-offset-1 left-nav">
		<%= render(partial: '/layouts/info_menu', locals: { network: @network, active_item: "details"}) %>
	</div>
	<%= render partial: 'related_dropdown', locals: { network: @network } %>
	<div class="col-md-9 col-xs-12 main">
		<div class="info-header">
			<div class="row">
				<div class="col-md-9 col-xs-12">
					<%= render(partial: 'networks/network_main_info_header', locals: { network: @network }) %>
				</div>
			</div>
		</div>
		<div class="content">
			<div class="row">
				<div class="col-md-9 col-xs-12">
					<div class="row">
						<div class="col-md-4 label">
			            	<label class="form-label">Preview</label>
			            	<p class="form-guidance">Please crop as a square. Crop the symbol and not the name if possible.</p>
			            </div>
            			<div class="col-md-8">
			            	<%= image_tag @network.logo_url(:large), id: "cropbox" %>
			            </div>
	           			<%= form_for @network do |f| %>
				            <% %w[x y w h].each do |attribute| %>
								<%= f.hidden_field "crop_#{attribute}" %>
							<% end %>
	          				<ul class="action-links">
					          <li class="submit">
					            <%= f.submit "Crop", class: "form-submit" %> 
					          </li>
					        </ul>
	          			<% end %>
		          	</div>
		        </div>
			</div>
		</div>
	</div>
</div>

app/views/networks/follow.js.erb
<% if @success %>
	$(".action-links > li:first-child").html("<%= escape_javascript link_to('Following #{@network.name}', unfollow_network_path, remote: true, method: :put, class: 'action-link', id: 'following-network', accesskey: 'F') %>");
	$("#following-network").text("Following " + "<%= escape_javascript @network.name %>");
	$(".notice").show();
	$(".notice").html("<%= flash.now[:notice] %>")
	$(".notice").delay(2000).fadeOut(400);
<% else %>

<% end %>

app/views/networks/log.js.erb
$('.main').html("<%= j (render 'log') %>");
$('#info-menu > li').removeClass("active-item");
$('#log').addClass("active-item");
$('.action-links').hide();

app/views/networks/new.html.erb
<% provide(:title, 'Add new network') %> 
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="info-header">
			<div class="row">
				<div class="col-md-8 col-md-offset-4">
					<h1>Add a new network</h1>
				</div>
			</div>
			<%= render partial: 'form', locals: {is_new: true} %>
		</div>
	</div>
</div>

app/views/networks/whitepapers.html.erb
<%= render '/whitepapers/whitepaper_list' %>