config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}, sign_up: 'signup', sign_in: 'login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
  
  resources :categories
  
  resources :newsletters do
    get :prevent_display
    get :restore_cookie
  end

  resources :users do
    get :following
    get :activity
  end

  resources :comments do
    resources :comments
  end

  resources :searches

  resources :networks do
    member do
      put :follow
      put :unfollow
      get :logs
    end

    resources :whitepapers

    resources :coins do
      member do
        put :follow
        put :unfollow
        get :logs
        get :ico
        get :edit_ico
      end
    end

    resources :links, path: :questions do 
      resources :comments do
        resources :comments
      end
    end

  end

  resources :links, path: :questions do 
    resources :comments do
      resources :comments
    end
  end

  resources :whitepapers

  require 'sidekiq/web'
  
  mount Sidekiq::Web => '/sidekiq'
  
  get '/account/', to:"users#edit"
  
  get '/account/:id', to:"users#edit"

  get 'finish/:id/', to: 'users#finish', :as => :finish

  get 'about', to: 'users#index', :as => :about

  get 'sales', to: 'coins#sales', :as => :sales

  get 'search', to: 'searches#results', :as => :results

  get 'coin_search', to: 'searches#coin_search', :as => :coin_search

  get 'network_search', to: 'searches#network_search', :as => :network_search

  get 'network_match', to: 'searches#network_match', :as => :network_match

  get 'networks/:network_id/coin/:id/add_network', to: 'coins#add_network', :as => :add_network_to_coin

  get 'questions', to: 'links#index', :as => :questions

  get 'loaderio-f78e3355deb50cdf9149e06780c03507', to: 'users#loader'

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
    get 'signin', to: 'devise/sessions#new'
  end

  get ':username', to: 'users#show', :as => :current_user
  
  get ':username/edit', to: 'users#edit', :as => :edit_current_user
  
  get ':username/activity', to: 'users#activity', :as => :current_user_activity

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def results
		@query = params[:query]
		@coin_results = Coin.search(params[:query]) 
		@network_results = Network.search(params[:query]) 
		@whitepaper_results = Whitepaper.search(params[:query])
		result_categories = []
		@coin_results.each do |result|
			result_categories << result.category
		end
		@network_results.each do |result|
			result_categories << result.category
		end
		@result_categories = result_categories.uniq
	end

	def coin_search
		@query = params[:query]
		@network = Network.friendly.find(params[:network])
		@coin_results = Coin.search(params[:query])
		respond_to do |format|
	        format.js 
	    end
	end

	def network_search
		@query = params[:query]
		puts "query is #{@query}"
		@network_results = Network.search(params[:query])
		respond_to do |format|
	        format.js 
	    end
	end

	def network_match
		@query = params[:query]
		@network = Network.friendly.find(params[:network])
		query_length = @query.length
		@network.coins.each do |coin|
			if(coin.name[0..query_length - 1].downcase == @query.downcase)
				@matching_coin = coin
			else
				@matching_coin
			end
		end
		respond_to do |format|
	        format.js 
	    end
	end
	
end

app/views/searches/_filters.html.erb
<div class="col-md-2 col-md-offset-1 left-nav">
	<ul class="info-menu status-info-menu" id="search-status-info-menu">
		<li id="status-show-all" data-status="all" class="active-item">
			<p>All statuses</p>
		</li>
		<li class="status-link" data-status="live">
			<p>Live</p>
		</li>
		<li class="status-link" data-status="preproduction">
			<p>Preproduction</p>
		</li>
		<li class="status-link" data-status="concept">
			<p>Concept</p>
		</li>
	</ul>	
	<ul class="info-menu category-info-menu" id="search-category-info-menu">
		<li id="category-show-all" class="active-item" data-category="all"><p>All categories</p></li>
		<% @result_categories.each do |category| %>
			<% unless category.nil? %>
				<li class="category-link" id=<%= category.name.gsub(/\s+/, "").downcase %> data-category=<%= category.name.gsub(/\s+/, "").downcase %>>
						<p><%= category.name.capitalize %></p>
				</li>
			<% end %>
		<% end %>
	</ul>
</div>

app/views/searches/coin_search.js.erb
$('.quick-search-results').html('<%= escape_javascript(render partial: "coins/coin_search", locals: { coin_results: @coin_results, network: @network }) %>');

app/views/searches/network_match.js.erb
<% if @matching_coin.blank? %>
<%#
	$("label").css('opacity', 1.0);
	$("textarea").prop('disabled', false);
	$("select").prop('disabled', false);
	$("input").prop('disabled', false);
%>
	$('.quick-search-results').html("");
<% else %>
<%#
	$("label").css('opacity', 0.5);
	$("textarea").prop('disabled', true);
	$("select").prop('disabled', true);
	$("input").not("#coin_name").prop('disabled', true);
%>
	$('.quick-search-results').html('<%= escape_javascript(render partial: "networks/network_match") %>');
<% end %>

app/views/searches/network_search.js.erb
<% if @network_results.blank? %>
<%#
	$("label").css('opacity', 1.0);
	$("textarea").prop('disabled', false);
	$("select").prop('disabled', false);
	$(".new_network > input").prop('disabled', false);
%>
	$('.quick-search-results').html("");
<% else %>
<%#
	$("label").not("#name-label").css('opacity', 0.5);
	$("textarea").prop('disabled', true);
	$("select").prop('disabled', true);
	$(".new_network > input").not("#network_name").prop('disabled', true);
%>	
	$('.quick-search-results').html('<%= escape_javascript(render partial: "networks/network_search", locals: { network_results: @network_results }) %>');
<% end %>

app/views/searches/results.html.erb
<div class="row">
	<%= render 'filters', object: @categories %>
	<div class="col-md-6 col-md-offset-1 col-xs-12 main">
		<ul>
			<li class="search-block block">
					<div class="row results network-results">
						<div class="col-md-12 col-xs-12">
							<h1 class="list-name">Networks matching '<%= @query %>'</h1>
							<% if @network_results.empty? %>
								<p>No networks found. <%= link_to "Add one?", new_network_path %></p>
							<% else %>
								<% @network_results.each_with_index do |result, i| %>
									<%= render '/networks/network_widget', :network => result, :i => i %>
								<% end %>
							<% end %>
						</div>
					</div>
					<div class="row results coin-results">
						<div class="col-md-12 col-xs-12">
							<h1 class="list-name">Coins matching '<%= @query.downcase %>'</h1>
							<% if @coin_results.empty? %>
								<p>No coins found. Navigate to the <%= link_to "network", networks_url %> you think the coin belongs to and add it there.</p>
								<p>If that network doesn't exist, <%= link_to "add it", new_network_path %>.</p>
							<% else %>
								<% @coin_results.each_with_index do |result, i| %>
									<%= render '/coins/coin_widget', :coin => result, :i => i %>
								<% end %>
							<% end %>
						</div>
					</div>
					<div class="row results">
						<div class="col-md-12 col-xs-12">
							<h1 class="list-name">Whitepapers matching '<%= @query %>'</h1>
							<% if @whitepaper_results.empty? %>
								<p>No whitepapers found. Navigate to the <%= link_to "network", networks_url %> you think the whitepaper belongs to and add it there.</p>
								<p>If that network doesn't exist, <%= link_to "add it", new_network_path %>.</p>
							<% else %>
								<% @whitepaper_results.each do |wp| %>
									<%= render 'whitepapers/single_whitepaper_result', :wp => wp, :network => wp.network %>
								<% end %>
							<% end %>
						</div>
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>
<ul class="action-links">
	<li><%= link_to("Add new network", new_network_path, class: "action-link", accesskey: 'A') %></li>
</ul>